### ISSUE TITLE
[openvpn] missing library after bump to 2.6

### ISSUE THREAD

**Issue by harryboo** [Freetz-NG/freetz-ng#717]
OpenVPN doesnt compile. Compilation stops with:
```
checking for setcon in -lselinux... no
checking for pam_start in -lpam... no
checking for PKCS11_HELPER... no
checking for LIBCAPNG... no
configure: error: libcap-ng package not found. Is the development package and pkg-config installed?

make[1]: *** [make/pkgs/openvpn/openvpn.mk:79: source/target-mips_gcc-5.5.0_uClibc-0.9.33.2-nptl_kernel-3.10/openvpn-2.6.0/.configured] Beendet
```
from the changelog:
> GitHub Actions: Add new libcap-ng-dev dependency

**Comment by fda77** [comment]
There are still other problems
```
event.c: In function 'po_del':
event.c:732:24: error: invalid use of undefined type 'struct pollfd'
         if (pos->events[i].fd == event)
                        ^
event.c:732:24: error: dereferencing pointer to incomplete type 'struct pollfd'
event.c:737:28: error: invalid use of undefined type 'struct pollfd'
                 pos->events[j] = pos->events[j+1];
                            ^
event.c:737:45: error: invalid use of undefined type 'struct pollfd'
                 pos->events[j] = pos->events[j+1];
                                             ^
event.c:737:17: error: invalid use of undefined type 'struct pollfd'
                 pos->events[j] = pos->events[j+1];
                 ^~~
event.c: In function 'po_set_pollfd_events':
event.c:752:25: error: 'POLLOUT' undeclared (first use in this function); did you mean 'POLL_OUT'?
         pfdp->events |= POLLOUT;
                         ^~~~~~~
                         POLL_OUT
...
```
