### PR TITLE
iksemel migration (not just version bump)

### PR DESCRIPTION
**Pull request by pfichtner**
When compiling asterisks I run into this issue
```
libtool: compile:  /tmp/workspace.1XL7yKca3F/toolchain/build/mips_gcc-4.8.5_uClibc-0.9.33.2-nptl/mips-linux-uclibc/bin/mips-linux-uclibc-gcc -DHAVE_CONFIG_H -I. -I../include -I../include -march=24kc -mtune=24kc -msoft-float -Os -pipe -Wa,--trap -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 --std=gnu99 -Wall -I/tmp/workspace.1XL7yKca3F/toolchain/build/mips_gcc-4.8.5_uClibc-0.9.33.2-nptl/mips-linux-uclibc/usr/include -march=24kc -mtune=24kc -msoft-float -Os -pipe -Wa,--trap -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 --std=gnu99 -Wall -MT libiksemel_la-tls-gnutls.lo -MD -MP -MF .deps/libiksemel_la-tls-gnutls.Tpo -c tls-gnutls.c -o libiksemel_la-tls-gnutls.o >/dev/null 2>&1
mv -f .deps/libiksemel_la-tls-gnutls.Tpo .deps/libiksemel_la-tls-gnutls.Plo
/bin/bash ../libtool  --tag=CC   --mode=compile /tmp/workspace.1XL7yKca3F/toolchain/build/mips_gcc-4.8.5_uClibc-0.9.33.2-nptl/mips-linux-uclibc/bin/mips-linux-uclibc-gcc -DHAVE_CONFIG_H -I. -I../include -I../include   -march=24kc -mtune=24kc -msoft-float -Os -pipe -Wa,--trap -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 --std=gnu99 -Wall  -I/tmp/workspace.1XL7yKca3F/toolchain/build/mips_gcc-4.8.5_uClibc-0.9.33.2-nptl/mips-linux-uclibc/usr/include -march=24kc -mtune=24kc -msoft-float -Os -pipe -Wa,--trap -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 --std=gnu99 -Wall -MT libiksemel_la-tls-openssl.lo -MD -MP -MF .deps/libiksemel_la-tls-openssl.Tpo -c -o libiksemel_la-tls-openssl.lo `test -f 'tls-openssl.c' || echo './'`tls-openssl.c
libtool: compile:  /tmp/workspace.1XL7yKca3F/toolchain/build/mips_gcc-4.8.5_uClibc-0.9.33.2-nptl/mips-linux-uclibc/bin/mips-linux-uclibc-gcc -DHAVE_CONFIG_H -I. -I../include -I../include -march=24kc -mtune=24kc -msoft-float -Os -pipe -Wa,--trap -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 --std=gnu99 -Wall -I/tmp/workspace.1XL7yKca3F/toolchain/build/mips_gcc-4.8.5_uClibc-0.9.33.2-nptl/mips-linux-uclibc/usr/include -march=24kc -mtune=24kc -msoft-float -Os -pipe -Wa,--trap -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 --std=gnu99 -Wall -MT libiksemel_la-tls-openssl.lo -MD -MP -MF .deps/libiksemel_la-tls-openssl.Tpo -c tls-openssl.c  -fPIC -DPIC -o .libs/libiksemel_la-tls-openssl.o
tls-openssl.c: In function 'my_bio_create':
tls-openssl.c:27:3: error: dereferencing pointer to incomplete type
  b->init = 1;
   ^
tls-openssl.c:28:3: error: dereferencing pointer to incomplete type
  b->num = 0;
   ^
tls-openssl.c:29:3: error: dereferencing pointer to incomplete type
  b->ptr = NULL;
   ^
tls-openssl.c:30:3: error: dereferencing pointer to incomplete type
  b->flags = 0 ;
   ^
tls-openssl.c: In function 'my_bio_destroy':
tls-openssl.c:39:3: error: dereferencing pointer to incomplete type
  b->ptr = NULL;
   ^
tls-openssl.c:40:3: error: dereferencing pointer to incomplete type
  b->init = 0;
   ^
tls-openssl.c:41:3: error: dereferencing pointer to incomplete type
  b->flags = 0;
   ^
tls-openssl.c: In function 'my_bio_read':
tls-openssl.c:48:53: error: dereferencing pointer to incomplete type
  struct ikstls_data *data = (struct ikstls_data *) b->ptr;
                                                     ^
tls-openssl.c: In function 'my_bio_write':
tls-openssl.c:61:53: error: dereferencing pointer to incomplete type
  struct ikstls_data *data = (struct ikstls_data *) b->ptr;
                                                     ^
tls-openssl.c: At top level:
tls-openssl.c:92:1: error: variable 'my_bio_method' has initializer but incomplete type
 static BIO_METHOD my_bio_method = {
 ^
tls-openssl.c:93:2: warning: excess elements in struct initializer [enabled by default]
  ( 100 | 0x400 ),
  ^
tls-openssl.c:93:2: warning: (near initialization for 'my_bio_method') [enabled by default]
tls-openssl.c:94:2: warning: excess elements in struct initializer [enabled by default]
  "iksemel transport",
  ^
tls-openssl.c:94:2: warning: (near initialization for 'my_bio_method') [enabled by default]
tls-openssl.c:95:2: warning: excess elements in struct initializer [enabled by default]
  my_bio_write,
  ^
tls-openssl.c:95:2: warning: (near initialization for 'my_bio_method') [enabled by default]
tls-openssl.c:96:2: warning: excess elements in struct initializer [enabled by default]
  my_bio_read,
  ^
tls-openssl.c:96:2: warning: (near initialization for 'my_bio_method') [enabled by default]
tls-openssl.c:97:2: warning: excess elements in struct initializer [enabled by default]
  my_bio_puts,
  ^
tls-openssl.c:97:2: warning: (near initialization for 'my_bio_method') [enabled by default]
tls-openssl.c:98:2: warning: excess elements in struct initializer [enabled by default]
  my_bio_gets,
  ^
tls-openssl.c:98:2: warning: (near initialization for 'my_bio_method') [enabled by default]
tls-openssl.c:99:2: warning: excess elements in struct initializer [enabled by default]
  my_bio_ctrl,
  ^
tls-openssl.c:99:2: warning: (near initialization for 'my_bio_method') [enabled by default]
tls-openssl.c:100:2: warning: excess elements in struct initializer [enabled by default]
  my_bio_create,
  ^
tls-openssl.c:100:2: warning: (near initialization for 'my_bio_method') [enabled by default]
tls-openssl.c:102:1: warning: excess elements in struct initializer [enabled by default]
 };
 ^
tls-openssl.c:102:1: warning: (near initialization for 'my_bio_method') [enabled by default]
tls-openssl.c: In function 'tls_handshake':
tls-openssl.c:138:5: error: dereferencing pointer to incomplete type
  bio->ptr = (void *) data;
     ^
make[2]: *** [Makefile:564: libiksemel_la-tls-openssl.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
libtool: compile:  /tmp/workspace.1XL7yKca3F/toolchain/build/mips_gcc-4.8.5_uClibc-0.9.33.2-nptl/mips-linux-uclibc/bin/mips-linux-uclibc-gcc -DHAVE_CONFIG_H -I. -I../include -I../include -march=24kc -mtune=24kc -msoft-float -Os -pipe -Wa,--trap -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 --std=gnu99 -Wall -I/tmp/workspace.1XL7yKca3F/toolchain/build/mips_gcc-4.8.5_uClibc-0.9.33.2-nptl/mips-linux-uclibc/usr/include -march=24kc -mtune=24kc -msoft-float -Os -pipe -Wa,--trap -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 --std=gnu99 -Wall -MT libiksemel_la-stream.lo -MD -MP -MF .deps/libiksemel_la-stream.Tpo -c stream.c -o libiksemel_la-stream.o >/dev/null 2>&1
mv -f .deps/libiksemel_la-stream.Tpo .deps/libiksemel_la-stream.Plo
make[2]: Leaving directory '/tmp/workspace.1XL7yKca3F/source/target-mips_gcc-4.8.5_uClibc-0.9.33.2-nptl/iksemel-978b733462/src'
make[1]: *** [Makefile:452: all-recursive] Error 1
make[1]: Leaving directory '/tmp/workspace.1XL7yKca3F/source/target-mips_gcc-4.8.5_uClibc-0.9.33.2-nptl/iksemel-978b733462'
```

There's an issue in the project which is still open https://github.com/meduketto/iksemel/issues/52

Since the last commit in the project was in 2011-10 (yes no typo: 2011 not 2021) I started looking for forks and got it working using https://github.com/timothytylee/iksemel-1.4

I have no clue if this is a good nor the best choice (and even I can't get asterisk compiling but got over this issue)

### CODE REVIEW

**Comment by fda77** [comment]
The problem with openssl may depend on the openssl version you selected in freetz! Old programms are not compatible with newer versions, and new progs could have dropped support for old openssl

Formal: docs/CHANGELOG.md is unchanged, $(PKG)_SITE never ends with "/" in freetz (dont know the reason, seems to work also with)

**Comment by pfichtner** [comment]
> The problem with openssl may depend on the openssl version you selected in freetz! Old programms are not compatible with newer versions, and new progs could have dropped support for old openssl

Did try with openssl 1.1.1 as well with 3.0.1 (which is marked as experimental). Could try with openssl version 1.0.2 (which is marked as deprecated).

**Comment by fda77** [comment]
1.0 is deprecated, but it fits to a software of 2011. The Openssl api changes

**Comment by pfichtner** [comment]
> The problem with openssl may depend on the openssl version you selected in freetz! Old programms are not compatible with newer versions, and new progs could have dropped support for old openssl
> 
> Formal: docs/CHANGELOG.md is unchanged, $(PKG)_SITE never ends with "/" in freetz (dont know the reason, seems to work also with)

You're right: iksemel builds well with openssl 1.0.2. From asterisk's point of view this doesn't make a difference because asterisk, which depends on iksemel, itself only compiles against  openssl 1.0.2. Since my goal is to compile asterisk for me it makes no difference whether iksemel as dependency compiles or not when asterisk doesn't. 

What I've tested so long
| package         | openssl 1.0.2 | openssl 1.1.1 | openssl 3.0.1 |
| --------------- | ------------- | ------------- | ------------- |
| iksemel ("old") | yes           | no            | no            |
| iksemel ("new") | yes           | yes           | yes           |
| asterisk        | yes           | no            | no            |

So please decide whether to close this PR unmerged or not. If not I'd try to fix the points you mentioned in your first comment. 


PS: Just for reference: asterisk fails to compile with an error that reminds me of the issue #437 
```
libasteriskssl.c:82:26: error: macro "SSL_library_init" passed 1 arguments, but takes just 0
 int SSL_library_init(void)
                          ^
libasteriskssl.c:83:1: error: expected '=', ',', ';', 'asm' or '__attribute__' before '{' token
 {
 ^
libasteriskssl.c:92:33: error: macro "SSL_load_error_strings" passed 1 arguments, but takes just 0
 void SSL_load_error_strings(void)

```

**Comment by fda77** [comment]
Wenn es dein Ziel ist Asterisk zu nutzen, wäre es wohl am besten davon eine neuere Version zu nutzen. In Freetz ist v11, aktuell ist v18... Die alte dürfte unsicher sein, wobei man dafür keinen Port freigeben muss

Bei Fedroa ist iksemel auch keine Abhängigkeit mehr. Allerdings einige andere
```
ldd /usr/sbin/asterisk
        libasteriskpj.so.2 => /lib64/libasteriskpj.so.2 (0x0000ffff90f9b000)
        libasteriskssl.so.1 => /lib64/libasteriskssl.so.1 (0x0000ffff911bf000)
        libcap.so.2 => /lib64/libcap.so.2 (0x0000ffff9085c000)
        libcrypto.so.1.1 => /lib64/libcrypto.so.1.1 (0x0000ffff90908000)
        libcrypt.so.2 => /lib64/libcrypt.so.2 (0x0000ffff9087d000)
        libc.so.6 => /lib64/libc.so.6 (0x0000ffff90562000)
        libdl.so.2 => /lib64/libdl.so.2 (0x0000ffff90dd8000)
        libedit.so.0 => /lib64/libedit.so.0 (0x0000ffff90721000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x0000ffff90531000)
        libjansson.so.4 => /lib64/libjansson.so.4 (0x0000ffff908e7000)
        /lib/ld-linux-aarch64.so.1 (0x0000ffff91509000)
        liblzma.so.5 => /lib64/liblzma.so.5 (0x0000ffff904bd000)
        libm.so.6 => /lib64/libm.so.6 (0x0000ffff90798000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x0000ffff9083b000)
        libresolv.so.2 => /lib64/libresolv.so.2 (0x0000ffff90775000)
        libsqlite3.so.0 => /lib64/libsqlite3.so.0 (0x0000ffff90c84000)
        libssl.so.1.1 => /lib64/libssl.so.1.1 (0x0000ffff90bd0000)
        libtinfo.so.6 => /lib64/libtinfo.so.6 (0x0000ffff9047c000)
        libuuid.so.1 => /lib64/libuuid.so.1 (0x0000ffff908c6000)
        libxml2.so.2 => /lib64/libxml2.so.2 (0x0000ffff90df9000)
        libz.so.1 => /lib64/libz.so.1 (0x0000ffff90500000)
        linux-vdso.so.1 (0x0000ffff91546000)
```
Wahrscheinlich wird man das meiste durch configure deaktivieren können, man müsste schauen welche libs in Freetz fehlen. Auf Verschlüsselung kann man auch verzichten, da diese nur bis zum Provider geht, also nutzlos. Für Telekom+ssl braucht man eh noch einen zusätzlichen Patch für Asterisk, da die Telekom durch Erweiterung von Standards zeigen möchte wie gut sie ist
Ich hab dich mal eingeladen, dann kannst du PR selbst bearbeiten und auch moderieren, soweit das mit github überhaupt geht

**Comment by pfichtner** [comment]
> Wenn es dein Ziel ist Asterisk zu nutzen, wäre es wohl am besten davon eine neuere Version zu nutzen. In Freetz ist v11, aktuell ist v18... Die alte dürfte unsicher sein, wobei man dafür keinen Port freigeben muss

Ich finde asterisk auf der FritzBox sehr charmant, habe es allerdings selbst noch nie ausprobiert da mir die Möglichkeiten welche AVM bieten gerade so noch ausreichen. Ich liebäugel allerdings immer damit, asterisk auszuprobieren/nutzen zu wollen und wenn, wäre mein Wunsch asterisk auf der FritzBox, und nich auf dem lokalen Server, RasPi, o.ä.) laufen zu lassen. 

Dass die asterisk Version in Freetz schon recht abgehangen ist war mir auch aufefallen. Gibt es dafür technische Gründe, dass ein upgrade schwierig/unmöglich ist oder lag es eher daran, dass kein Bedarf und damit auch kein Interesse besteht/bestand?

**Comment by fda77** [comment]
Ich kenne keinen Grund warum eine aktuelle Version nicht funktionieren sollte. Es müsste halt jemand machen.. Das Package ist durch diverse Module etwas umfangreicher wie ein durchschnittliches Package.
Ich verwende Asterisk auf einem Raspberry, seit AVM Voip am Hybridanschluss mit FOS 7.25 unbrauchbar gemacht hat. Ob es mittlerweile wieder funktioniert hab ich nicht ausprobiert. Bei AVM hat man immer das Problem dass sich durch "Sicherheitsupdates" eine Funktion ändern kann die man bislang genutzt hat. Durch Fedora erhalte ich automatische Updates ohne selbst was machen zu müssen :)
Rückblickend hätte ich besser Asterisk schon viel früher verwenden sollen! Es hat viele und toll Funktionen und ist mir allen möglichen Geräten und Apps kompatible. Allerdings ist die Grundkonfiguration wesentlich komplizierter
